language: python
python:
  - "3.8"

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run --rm api sh -c "python3 manage.py test"

env:
  - SECRET_KEY=0000 ADMIN_KEY=0000 DEBUG=0 WRITE_FILES=0 ALLOWED_HOSTS="*" PORT=8000
