version: "3"

services:
  api:
    build:
      context: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./app:/app
    command: >
      sh -c "gunicorn api.wsgi -b 0.0.0.0:${PORT} ${GUNICORN_CMD_ARGS}"
