# EXTRACTING [CHARS]
MIN_CONTENT_LENGTH = 250
MAX_CONTENT_LENGTH = 5000

# ANSWERING [CHARS]
MIN_ANSWER_LENGTH = 1
MAX_ANSWER_LENGTH = 500

# SUMMARIZATION [WORDS]
MIN_SUMMARY_LENGTH = 50
MAX_SUMMARY_LENGTH = 300
