# Generated by Django 3.1.7 on 2021-05-08 15:16

from django.db import migrations, models
import django.utils.timezone
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(max_length=511)),
                ('summary', models.TextField(max_length=4095)),
            ],
        ),
        migrations.CreateModel(
            name='KeyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('tester_name', models.CharField(max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('use_count', models.IntegerField(default=0)),
                ('use_limit', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='ResultPageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('references', django_mysql.models.ListCharField(models.CharField(max_length=255), max_length=13005, size=50)),
                ('content', models.TextField(blank=True, default=None, null=True)),
                ('quality', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
