# Generated by Django 3.1.7 on 2021-05-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keymodel',
            name='tester_class',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
