# Generated by Django 3.1.7 on 2021-04-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210411_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultpagemodel',
            name='content',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='resultpagemodel',
            name='quality',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
