# Generated by Django 3.1.7 on 2021-06-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_keymodel_last_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keymodel',
            name='last_used',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
