# Generated by Django 3.1.7 on 2021-05-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_keymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='keymodel',
            name='use_limit',
            field=models.IntegerField(default=10),
        ),
    ]
