# Generated by Django 3.1.7 on 2021-05-08 15:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PollModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('phrase', models.CharField(max_length=255)),
                ('answer_model', models.IntegerField()),
                ('summary_model', models.IntegerField()),
                ('page_number', models.IntegerField()),
                ('answer_score', models.FloatField()),
                ('summary_score', models.FloatField()),
                ('time_score', models.FloatField()),
                ('answer', models.TextField(blank=True, default=None, null=True)),
                ('summary', models.TextField(blank=True, default=None, null=True)),
                ('comment', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
