# Generated by Django 3.1.7 on 2021-05-03 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PollModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('subject_name', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
                ('phrase', models.CharField(max_length=255)),
                ('answer_model', models.IntegerField()),
                ('summary_model', models.IntegerField()),
                ('answer_score', models.FloatField()),
                ('summary_score', models.FloatField()),
                ('answer', models.TextField(blank=True, default=None, null=True)),
                ('summary', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
