# Generated by Django 3.1.7 on 2021-05-03 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210503_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollmodel',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 5, 3, 18, 47, 26, 932238)),
        ),
    ]
