# Generated by Django 3.1.7 on 2021-06-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210513_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollmodel',
            name='execution_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pollmodel',
            name='time_score',
            field=models.FloatField(default=0),
        ),
    ]
