# Generated by Django 3.1.7 on 2021-05-04 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210504_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollmodel',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
